name: Benchmark

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Push name"
        default: "Bencher push"
  schedule:
    - cron: '12 3 * * *'

jobs:
  bencher:
    name: Disk performance
    runs-on: ubuntu-22.04
    env:
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup dependencies
      run: |
          sudo apt-get update -qq
          sudo apt-get install -qq linux-libc-dev libuv1-dev

    - name: Configure
      run: |
          autoreconf -i
          ./configure --enable-benchmark --enable-debug --without-lz4

    - name: Build
      run: |
          make benchmark/run -j$(nproc --all)

    - uses: bencherdev/bencher@v0.3.6
    - name: Benchmark with Bencher
      run: |
          for engine in pwritev2 uring kaio; do
            for buf in 4096 65536; do
              for mode in buffered direct; do
                ./benchmark/run disk -e $engine -b $buf -m $mode
              done
            done
          done | bencher run --project raft
