name: Benchmark

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Push name"
        default: "Bencher push"
  schedule:
    - cron: '12 3 * * *'

jobs:
  bencher:
    name: Disk performance
    runs-on: ubuntu-22.04
    env:
      BENCHER_PROJECT: raft
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
      BENCHER_TESTBED: github-ubuntu-22-04
    steps:
    - uses: actions/checkout@v3
    - name: Setup dependencies
      run: |
          sudo apt-get update -qq
          sudo apt-get install -qq linux-libc-dev libuv1-dev

    - name: Configure
      run: |
          autoreconf -i
          ./configure --enable-benchmark --enable-debug --without-lz4

    - name: Build
      run: |
          make benchmark/run -j$(nproc --all)

    - uses: bencherdev/bencher@v0.3.6
    - name: Run benchmark and send results to Bencher
      run: |
          bencher run \
            --if-branch "$GITHUB_REF_NAME" \
            --else-if-branch "$GITHUB_BASE_REF" \
            --else-if-branch main \
            --err \
            --github-actions ${{ secrets.GITHUB_TOKEN }} \
            "./benchmark/run disk -e uring,kaio,pwritev2 -b 4096,65536 -m direct,buffered"
