name: Checks

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup dependencies
      run: |
          sudo apt-get update -qq
          sudo apt-get install -qq lcov linux-libc-dev liblz4-dev libuv1-dev btrfs-progs xfsprogs zfsutils-linux

    - name: Build
      run: |
          git clone --depth 1 https://github.com/edlund/amalgamate.git
          export PATH=$PATH:$PWD/amalgamate
          autoreconf -i
          ./configure --enable-example --enable-debug --enable-code-coverage --enable-sanitize
          amalgamate.py --config=amalgamation.json --source=$(pwd)
          gcc raft.c -c -D_GNU_SOURCE -DHAVE_LINUX_AIO_ABI_H -Wall -Wextra -Wpedantic -fpic

    - name: Test
      run: |
          export LIBRAFT_TRACE=1
          ./test/lib/fs.sh setup
          make -j$(nproc --all) check $(./test/lib/fs.sh detect) || (cat ./test-suite.log && false)
          ./test/lib/fs.sh teardown

    - name: Coverage
      run: |
          make code-coverage-capture

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true

  lint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: 'src test example'
        exclude: 'test/lib/munit.*'
        extensions: 'c,h'
        clangFormatVersion: 14
        style: file
