name: Coverity
on:
  push:
    branches:
      - main

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq linux-libc-dev libuv1-dev
      - name: Configure
        run: |
          autoreconf -i
          mkdir build
          cd build
          ../configure
      - uses: vapier/coverity-scan-action@v1
        with:
          email: free@ekanayaka.io
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          version: main
          description: ${GITHUB_SHA}
          command: make -C build -j$(nproc)
