name: Coverity
on:
  push:
    branches:
      - main

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vapier/coverity-scan-action@v1
        with:
          email: free@ekanayaka.io
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
